[package]
name = "mini_http_server"
version = "0.1.0"
edition = "2021"

# no web frameworks were harmed in the making of this project
[dependencies]
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
httparse = "1.8"
